routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
 
    Route::group(['middleware' => 'install'], function() {
    Route::get('/', ['as' => 'main', 'uses' => 'MainController@redirect']);
    Route::get('locale/{locale}', ['as' => 'change_locale', 'uses' => 'MainController@changeLocale']);

    // Login
    Route::get('login', ['as' => 'get_login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'post_login', 'uses' => 'Auth\LoginController@login']);

    // Forgot Password
    Route::get('password/email', ['as' => 'get_email', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/email', ['as' => 'post_email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);

    // Reset Password

        Route::post('password/reset', ['as' => 'post_reset', 'uses' => 'Auth\ResetPasswordController@reset']);

    // Add to Queue
    Route::get('queue', ['as' => 'add_to_queue', 'uses' => 'AddToNewQueueController@index']);
    Route::post('queue', ['as' => 'post_add_to_queue', 'uses' => 'AddToNewQueueController@postDept']);
   /* Route::post('queue/dept/{department}/{elem}', ['as' => 'post__add_to_queue1', 'uses' => 'AddToQueueController@postDept1']);

*/

        Route::post('appointments', 'AppointmentsController@index', ['except' => ['show']]);


        Route::get('updatedisplay/{id}', 'UpdateDisplayController@index');
    // Display
        Route::get('display', ['as' => 'display', 'uses' => 'DisplayController@index']);
        
        Route::get('display/{id}', ['as' => 'multidisplay', 'uses' => 'DisplayController@index1']);

      
        Route::resource('specializations', 'SpecializationController', ['except' => ['show']]);
        
        




    // Authenticated
      Route::group(['middleware' => 'auth:users'], function() {
        // Logout
        Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

        // Dashboard
        Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
        Route::post('dashboard/settings', ['as' => 'dashboard_store', 'uses' => 'DashboardController@store']);

        // Calls
        Route::get('calls', ['as' => 'calls', 'uses' => 'CallController@index']);
        Route::post('calls', ['as' => 'post_call', 'uses' => 'CallController@newCall']);
        Route::post('calls/recall', ['as' => 'post_recall', 'uses' => 'CallController@recall']);

        Route::post('calls/status_update', ['as' => 'status_update', 'uses' => 'CallController@status_update']);

        
        Route::post('calls/dept/{department}', ['as' => 'post_dept', 'uses' => 'CallController@postDept']);
         Route::post('calls/dept/{department}/{elem}', ['as' => 'post_dept1', 'uses' => 'CallController@postDept1']);


        Route::post('calls/pack/{package}', ['as' => 'post_pack', 'uses' => 'CallController@postPack']);
        Route::get('calls/getDeparts','CallController@getDeparts');




        Route::resource('locations', 'LocationController', ['except' => ['show']]);

        Route::resource('departmentGrps', 'DepartmentGroupController', ['except' => ['show']]);

        Route::resource('doctors','DoctorController', ['except' => ['show']]);

        // Department
        Route::resource('departments', 'DepartmentController', ['except' => ['show']]);


        Route::resource('packages', 'PackageController', ['except' => ['show']]);

        Route::resource('help', 'HelpController', ['except' => ['show']]);
      //  Route::resource('calls/getDeparts}','CallController@getDeparts');

         Route::get('missed','HelpController@missed');


        Route::get('help/help','HelpController@help');

        Route::get('myform1/ajax/{id}/{tno}',array('as'=>'myform.ajax','uses'=>'HelpController@myformAjax1'));


 
        Route::resource('service', 'ServiceController', ['except' => ['show']]);

        

        // Counter
            Route::resource('counters', 'CounterController', ['except' => ['show']]);
          
            Route::resource('billingcounters', 'BillingCounterController', ['except' => ['show']]);

        //Reports
            Route::group(['prefix' => 'reports', 'as' => 'reports::'], function() {
            // User Report
            Route::get('user', ['as' => 'user', 'uses' => 'UserReportController@index']);
            Route::get('user/{user}/{date}', ['as' => 'user_show', 'uses' => 'UserReportController@show']);

            // Queue list
            Route::get('queuelist/{date}', ['as' => 'queue_list', 'uses' => 'QueueListReportController@index']);
            
            Route::get('queuelist1/{date}', ['as' => 'queue_list1', 'uses' => 'QueueListReportController@show']);
            
           

            // Monthly Report
            Route::get('monthly', ['as' => 'monthly', 'uses' => 'MonthlyReportController@index']);
            Route::get('monthly/{department}/{sdate}/{edate}', ['as' => 'monthly_show', 'uses' => 'MonthlyReportController@show']);

            // Statistical Report
            Route::get('statistical', ['as' => 'statistical', 'uses' => 'StatisticalReportController@index']);
            Route::get('statistical/{date}/{user}/{department}/{counter}', ['as' => 'statistical_show', 'uses' => 'StatisticalReportController@show']);

            // Missed
            Route::get('missed-overtime', ['as' => 'missed', 'uses' => 'MissedOvertimeReportController@index']);
            Route::get('missed-overtime/{date}/{user}/{counter}/{type}', ['as' => 'missed_show', 'uses' => 'MissedOvertimeReportController@show']);


        });

      Route::post('missed-overtime/reissue', ['as' => 'post_reissue', 'uses' => 'MissedOvertimeReportController@reissue']);


/*
            Route::get('token_report', ['as' => 'missed', 'uses' => 'TokenReportController@index']);
            Route::get('token_report/{date}/{user}/{counter}/{type}', ['as' => 'token_report', 'uses' => 'TokenReportController@show']);

*/



        Route::get('token_report', ['as' => 'token_report', 'uses' => 'TokenReportController@index']);
      /*  Route::post('token_report', ['as' => 'post_call', 'uses' => 'TokenReportController@newCall']);
        Route::post('token_report/recall', ['as' => 'post_recall', 'uses' => 'TokenReportController@recall']);
        Route::post('token_report/dept/{department}', ['as' => 'post_dept', 'uses' => 'TokenReportController@postDept']);
        Route::post('token_report/pack/{package}', ['as' => 'post_pack', 'uses' => 'TokenReportController@postPack']);
        Route::get('token_report/getDeparts','TokenReportController@getDeparts');
*/


       Route::post('token_report/reissue', ['as' => 'post_reissue', 'uses' => 'TokenReportController@reissue']);






           
        // Users
        Route::get('users/{user}/password', ['as' => 'get_user_password', 'uses' => 'UserController@getPassword']);
        Route::post('users/{user}/password', ['as' => 'post_user_password', 'uses' => 'UserController@postPassword']);
        Route::resource('users', 'UserController', ['except' => ['show', 'edit', 'update']]);

        // Settings
        Route::get('settings', ['as' => 'settings', 'uses' => 'SettingsController@index']);
        Route::post('settings', ['as' => 'post_settings', 'uses' => 'SettingsController@update']);
        Route::post('settings/company', ['as' => 'post_company', 'uses' => 'SettingsController@companyUpdate']);
        Route::post('settings/overmissed', ['as' => 'post_over_missed', 'uses' => 'SettingsController@overmissedUpdate']);
        Route::post('settings/locale', ['as' => 'post_locale', 'uses' => 'SettingsController@localeUpdate']);


        Route::get('time', ['as' => 'time', 'uses' => 'TimeController@index']);



    });
});


/*
Route::get('add_to_newqueue', ['as' => 'add_to_newqueue', 'uses' => 'AddToNewQueueController@index']);
Route::get('queue', ['as' => 'add_to_queue', 'uses' => 'AddToNewQueueController@index']);




Route::get('queue', ['as' => 'post_add_to_queue', 'uses' => 'AddToNewQueueController@postDept']);

*/
//post_add_to_queue
        // Users
      
        Route::resource('locationusers', 'LocationUserController');
        Route::get('locationusers/{id}', 'UserReportController@show');
        Route::get('locationusers/{user}/edit', ['as' => 'get_user_edit', 'uses' => 'UserController@edit']);




//schedulers
Route::get('time', ['as' => 'time', 'uses' => 'TimeController@index']);
Route::get('getrecords', ['as' => 'time', 'uses' => 'GetRecordController@index']);
Route::get('scheduleQueue', ['as' => 'time', 'uses' => 'ScheduleQueueController@index']);
Route::get('secondQueue', ['as' => 'time', 'uses' => 'SecondQueueController@index']);
Route::get('thirdQueue', ['as' => 'time', 'uses' => 'ThirdQueueController@index']);
Route::get('scheduleQueues', ['as' => 'time', 'uses' => 'ScheduleQueuesController@index']);
Route::get('checklist/{mob}', ['as' => 'time', 'uses' => 'CheckListController@index']);
Route::resource('mychecklist', 'CheckListController@checkList', ['except' => ['show']]);
Route::get('consultation', ['as' => 'consultation', 'uses' => 'ConsultationController@index']);
Route::get('nextdayconsultation', ['as' => 'consultation', 'uses' => 'NextDayConsultationController@index']);
Route::resource('testtimer', 'TestTimeCallController', ['except' => ['show']]);
Route::get('pptimer', ['as' => 'pptimer', 'uses' => 'PPTimeCallController@index']);
Route::get('nonpptimer', ['as' => 'nonpptimer', 'uses' => 'NonPPTimeCallController@index']);

//schedulers





//PPTimeCallController.php

app/Models/Location.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Location extends Model
{
    protected $fillable = ['name','code','location_id'];

    public function calls()
	{
		return $this->hasMany('App\Models\Call');
	}
    
    public function billincounter()
	{
		return $this->hasMany('App\Models\BillingCounter');
	}
    
    
    
    

	/*public function location()
	{
		return $this->belongsTo('App\Models\Location');
	}

	public function department()
	{
		return $this->belongsTo('App\Models\Department');
	}

	public function counter()
	{
		return $this->belongsTo('App\Models\Counter');
	}

	public function queue()
	{
		return $this->hasMany('App\Models\Queue');
	}
*/












}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'username', 'email', 'role', 'password' ,'location_id','department_id','counter_id'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    public function calls()
	{
		return $this->hasMany('App\Models\Call');
	}

	public function getRoleTextAttribute($value)
	{
		if($this->attributes['role']=='A') return trans('messages.mainapp.role.Administrator');

		return trans('messages.mainapp.role.Staff');
	}

    public function getIsAdminAttribute($value)
	{
		if($this->attributes['role']=='A') return true;

        return false;
	}
      public function department()
    {
        return $this->belongsTo('App\Models\Department');
    }

    public function counter()
    {
        return $this->belongsTo('App\Models\Counter');
    }
     public function location()
    {
        return $this->belongsTo('App\Models\Location');
    }


}

app/Http/Controllers/LocationController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Repositories\DepartmentRepository;
use App\Models\Department;
use App\Repositories\CounterRepository;
use App\Models\Counter;
use App\Repositories\CallRepository;
use App\Models\Call;
use App\Models\Location;


class LocationController extends Controller
{
    protected $locations;

    public function __construct(Location $locations)
    {
        $this->locations = $locations;
    }

    public function index()
    {

      //  $this->authorize('access', Location::class);

       $locations =  Location::where('id','>',0)->get();

        return view('user.locations.index', [
            'locations' =>$locations,
        ]);
    }

    public function create()
    {
       // dd($request->all());//$this->authorize('access', Location::class);

        return view('user.locations.create',['locations' => Location::all()]);
    }

    public function store(Request $request, Location $location)
    {
        //$this->authorize('access', Location::class);

        $this->validate($request, [
            'name' => 'required',
            'code' =>'required'
        ]);

      //  Department::create($request->all());

        $location->name = $request->name;
        $location->code = $request->code;
        $location->save();



        flash()->success('Location created');
        return redirect()->route('locations.index');
    }

    public function edit(Request $request, Location $location)
    {
      $locations = Location::all();
        return view('user.locations.edit', [
            'locations' => $locations,
            'location'  => $location
        ]);
    }

    public function update(Request $request, Location $location)
    {
        //$this->authorize('access', Location::class);

        $this->validate($request, [
            'name' => 'required',
            'code' =>'required',
        ]);

        $location->name = $request->name;
        /*$department->location = $request->location_id;
        $department->counter = $request->counter;*/
        $location->code = $request->code;
        $location->save();

        flash()->success('Location updated');
        return redirect()->route('locations.index');
    }

    public function destroy(Request $request, Location $location)
    {
        //$this->authorize('access', Location::class);

        $location->delete();

        flash()->success('Location deleted');
        return redirect()->route('locations.index');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Repositories\UserRepository;
use App\Models\User;
use App\Repositories\DepartmentRepository;
use App\Models\Department;
use App\Repositories\CounterRepository;
use App\Models\Counter;
use App\Models\Online;
use App\Models\Location;
use Illuminate\Support\Facades\Input;

class UserController extends Controller
{
    protected $users;

    public function __construct(UserRepository $users,DepartmentRepository $departments,CounterRepository $counters)
    {
        $this->users = $users;
        $this->departments = $departments;
        $this->counters = $counters;
    }

    public function index(Request $request)
    {

         $service_users = Online::all('user_id');

      foreach ($service_users as $service_user) {
            $service_user_id[]=$service_user->user_id;
      }
      
        $this->authorize('access', User::class);

        return view('user.users.index', [
            'users' => $this->users->getAll(),
            'departments' =>$this->departments->getAll(),
            'online_user' => $service_user_id,
        ]);
    }

    public function create(Request $request)
    {
        $this->authorize('access', User::class);
        
        return view('user.users.create',['departments' =>$this->departments->getAll(),
            'counters' =>$this->counters->getAll(),'locations' =>Location::all()
            ]);
    }

    public function store(Request $request)
    {
              // dd($request->all());
        $this->authorize('access', User::class);

        $this->validate($request, [
            'name' => 'bail|required',
            'username' => 'bail|required|min:6|unique:users,username',
            'email' => 'bail|required|email|unique:users,email',
            'password' => 'bail|required|min:6|confirmed',
        ]);
       
        $data = $request->all();
       // $data['role'] = 'S';
        $data['password'] = bcrypt($request->password);
       // $date['department_id'] = $request->department;

        //return $data;

        $user = User::create($data);

        flash()->success('User created');
        return redirect()->route('users.index');
    }

    public function getPassword(Request $request, User $user)
    {
        $this->authorize('access', User::class);

        if($user->id==$request->user()->id) abort(404);

        return view('user.users.password', [
            'cuser' => $user,
        ]);
    }

    public function postPassword(Request $request, User $user)
    {
        $this->authorize('access', User::class);

        if($user->id==$request->user()->id) abort(404);

        $this->validate($request, [
            'password' => 'required|confirmed|min:6',
        ]);

        $user->password = bcrypt($request->password);
        $user->save();

        flash()->success('Password changed');
        return redirect()->route('users.index');
    }

    public function destroy(Request $request, User $user)
    {
        $this->authorize('access', User::class);

        $user->delete();

        flash()->success('User deleted');
        return redirect()->route('users.index');
    }

    public function getDepartments(Request $request){
    $data =$request->option;
     return $subcategories  = Department::where('location_id','=',$data)->get();

    }
}

resources/views/user/locations/create.blade.php
@extends('layouts.app')

@section('title', trans('messages.add').' '.trans('messages.mainapp.menu.location'))

@section('content')
    <div id="breadcrumbs-wrapper">
        <div class="container">
            <div class="row">
                <div class="col s12 m12 l12">
                    <h5 class="breadcrumbs-title col s5" style="margin:.82rem 0 .656rem">{{ trans('messages.add') }} {{ trans('messages.mainapp.menu.location') }}</h5>
                    <ol class="breadcrumbs col s7 right-align">
                        <li><a href="{{ route('dashboard') }}">{{ trans('messages.mainapp.menu.dashboard') }}</a></li>
                        <li><a href="{{ route('locations.index') }}">{{ trans('messages.mainapp.menu.location') }}</a></li>
                        <li class="active">{{ trans('messages.add') }}</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col s12 m6 offset-m3" style="padding-top:10px;padding-bottom:10px">
                <a class="btn-floating waves-effect waves-light orange tooltipped right" href="{{ route('locations.index') }}" data-position="top" data-tooltip="{{ trans('messages.cancel') }}"><i class="mdi-navigation-arrow-back"></i></a>
                <form id="add" action="{{ route('locations.store') }}" method="post">
                    {{ csrf_field() }}
                    <div class="row">
                        <div class="input-field col s12">
                            <label for="name">{{ trans('messages.name') }}</label>
                            <input id="name" type="text" name="name" placeholder="{{ trans('messages.mainapp.menu.location') }} {{ trans('messages.name') }}" value="{{ old('name') }}" data-error=".name">
                            <div class="name">
                                @if($errors->has('name'))<div class="error">{{ $errors->first('name') }}</div>@endif
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="input-field col s12">
                            <label for="code">{{ trans('messages.location.code') }}</label>
                            <input id="code" type="text" name="code" placeholder="{{ trans('messages.location.code') }}" value="{{ old('code') }}" data-error=".code">
                            <div class="code">
                                @if($errors->has('code'))<div class="error">{{ $errors->first('code') }}</div>@endif
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <button class="btn waves-effect waves-light right" type="submit">
                                {{ trans('messages.save') }}<i class="mdi-content-save left"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $("#add").validate({
            rules: {
                name: {
                    required: true
                },
                code: {
                    required: true
                },
            },
            errorElement : 'div',
            errorPlacement: function(error, element) {
                var placement = $(element).data('error');
                if (placement) {
                    $(placement).append(error)
                } else {
                    error.insertAfter(element);
                }
            }
        });
    </script>
@endsection

resources/views/user/locations/edit.blade.php
@extends('layouts.app')

@section('title', trans('messages.edit').' '.trans('messages.mainapp.menu.location'))

@section('content')
    <div id="breadcrumbs-wrapper">
        <div class="container">
            <div class="row">
                <div class="col s12 m12 l12">
                    <h5 class="breadcrumbs-title col s5" style="margin:.82rem 0 .656rem">{{ trans('messages.edit') }} {{ trans('messages.mainapp.menu.location') }}</h5>
                    <ol class="breadcrumbs col s7 right-align">
                        <li><a href="{{ route('dashboard') }}">{{ trans('messages.mainapp.menu.dashboard') }}</a></li>
                        <li><a href="{{ route('locations.index') }}">{{ trans('messages.mainapp.menu.location') }}</a></li>
                        <li class="active">{{ trans('messages.edit') }}</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col s12 m6 offset-m3" style="padding-top:10px;padding-bottom:10px">
                <a class="btn-floating waves-effect waves-light orange tooltipped right" href="{{ route('locations.index') }}" data-position="top" data-tooltip="{{ trans('messages.cancel') }}"><i class="mdi-navigation-arrow-back"></i></a>
                <form id="edit" action="{{ route('locations.update', ['location' => $location->id]) }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <div class="row">
                        <div class="input-field col s12">
                            <label for="name">{{ trans('messages.name') }}</label>
                            <input id="name" type="text" name="name" placeholder="{{ trans('messages.mainapp.menu.location') }} {{ trans('messages.name') }}" value="{{ $location->name }}" data-error=".name">
                            <div class="name">
                                @if($errors->has('name'))<div class="error">{{ $errors->first('name') }}</div>@endif
                            </div>
                        </div>
                    </div>

                     
                    <div class="row">
                        <div class="input-field col s12">
                            <label for="code">{{ trans('messages.location.code') }}</label>
                            <input id="code" type="text" name="code" placeholder="{{ trans('messages.location.code') }}" value="{{ $location->code }}" data-error=".code">
                            <div class="code">
                                @if($errors->has('code'))<div class="error">{{ $errors->first('code') }}</div>@endif
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <button class="btn waves-effect waves-light right" type="submit">
                                {{ trans('messages.update') }}<i class="mdi-action-swap-vert left"></i>
                            </button>
                        </div>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $("#edit").validate({
            rules: {
                name: {
                    required: true
                },
                code: {
                    required: true
                },
            },
            errorElement : 'div',
            errorPlacement: function(error, element) {
                var placement = $(element).data('error');
                if (placement) {
                    $(placement).append(error)
                } else {
                    error.insertAfter(element);
                }
            }
        });
    </script>
@endsection

resources/views/user/locations/index.blade.php
@extends('layouts.app')

@section('title', trans('messages.mainapp.menu.location'))

@section('css')
    <link href="{{ asset('assets/js/plugins/data-tables/css/jquery.dataTables.min.css') }}" type="text/css" rel="stylesheet" media="screen,projection">
@endsection

@section('content')
    <div id="breadcrumbs-wrapper">
        <div class="container">
            <div class="row">
                <div class="col s12 m12 l12">
                    <h5 class="breadcrumbs-title col s5" style="margin:.82rem 0 .656rem">{{ trans('messages.mainapp.menu.location') }}</h5>
                    <ol class="breadcrumbs col s7 right-align">
                        <li><a href="{{ route('dashboard') }}">{{ trans('messages.mainapp.menu.dashboard') }}</a></li>
                        <li class="active">{{ trans('messages.mainapp.menu.location') }}</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col s12">
                <div class="card-panel">
                    <a class="btn-floating waves-effect waves-light tooltipped" href="{{ route('locations.create') }}" data-position="top" data-tooltip="{{ trans('messages.add') }} {{ trans('messages.mainapp.menu.location') }}"><i class="mdi-content-add left"></i></a>
                    <div class="divider" style="margin:15px 0 10px 0"></div>
                    <table id="location-table" class="display" cellspacing="0">
                        <thead>
                            <tr>
                                <th style="width:40px">#</th>
                                <th>retre</th>
                                <th>{{ trans('messages.location.code') }}</th>
                                <th style="width:63px">{{ trans('messages.actions') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($locations as $location)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $location->name }}</td>
                                    <td>{{ $location->code }}</td>
                                    <td>
                                        <a class="btn-floating btn-action waves-effect waves-light orange tooltipped" href="{{ route('locations.edit', ['locations' => $location->id]) }}" data-position="top" data-tooltip="{{ trans('messages.edit') }}"><i class="mdi-editor-mode-edit"></i></a>
                                        <a class="btn-floating btn-action waves-effect waves-light red tooltipped frmsubmit" href="{{ route('locations.destroy', ['locations' => $location->id]) }}" data-position="top" data-tooltip="{{ trans('messages.delete') }}" method="DELETE"><i class="mdi-action-delete"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script type="text/javascript" src="{{ asset('assets/js/plugins/data-tables/js/jquery.dataTables.min.js') }}"></script>
    <script>
        $(function() {
            $('#location-table').DataTable({
                "oLanguage": {
                    "sLengthMenu": "Show _MENU_",
                    "sSearch": "Search"
                },
                "columnDefs": [{
                    "targets": [ -1 ],
                    "searchable": false,
                    "orderable": false
                }]
            });
        });
    </script>
@endsection