routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
 
    Route::group(['middleware' => 'install'], function() {
    Route::get('/', ['as' => 'main', 'uses' => 'MainController@redirect']);
    Route::get('locale/{locale}', ['as' => 'change_locale', 'uses' => 'MainController@changeLocale']);

    // Login
    Route::get('login', ['as' => 'get_login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'post_login', 'uses' => 'Auth\LoginController@login']);

    // Forgot Password
    Route::get('password/email', ['as' => 'get_email', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
    Route::post('password/email', ['as' => 'post_email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);

    // Reset Password

        Route::post('password/reset', ['as' => 'post_reset', 'uses' => 'Auth\ResetPasswordController@reset']);

    // Add to Queue
    Route::get('queue', ['as' => 'add_to_queue', 'uses' => 'AddToNewQueueController@index']);
    Route::post('queue', ['as' => 'post_add_to_queue', 'uses' => 'AddToNewQueueController@postDept']);
   /* Route::post('queue/dept/{department}/{elem}', ['as' => 'post__add_to_queue1', 'uses' => 'AddToQueueController@postDept1']);

*/

        Route::post('appointments', 'AppointmentsController@index', ['except' => ['show']]);


        Route::get('updatedisplay/{id}', 'UpdateDisplayController@index');
    // Display
        Route::get('display', ['as' => 'display', 'uses' => 'DisplayController@index']);
        
        Route::get('display/{id}', ['as' => 'multidisplay', 'uses' => 'DisplayController@index1']);

      
        Route::resource('specializations', 'SpecializationController', ['except' => ['show']]);
        
        




    // Authenticated
      Route::group(['middleware' => 'auth:users'], function() {
        // Logout
        Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

        // Dashboard
        Route::get('dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
        Route::post('dashboard/settings', ['as' => 'dashboard_store', 'uses' => 'DashboardController@store']);

        // Calls
        Route::get('calls', ['as' => 'calls', 'uses' => 'CallController@index']);
        Route::post('calls', ['as' => 'post_call', 'uses' => 'CallController@newCall']);
        Route::post('calls/recall', ['as' => 'post_recall', 'uses' => 'CallController@recall']);

        Route::post('calls/status_update', ['as' => 'status_update', 'uses' => 'CallController@status_update']);

        
        Route::post('calls/dept/{department}', ['as' => 'post_dept', 'uses' => 'CallController@postDept']);
         Route::post('calls/dept/{department}/{elem}', ['as' => 'post_dept1', 'uses' => 'CallController@postDept1']);


        Route::post('calls/pack/{package}', ['as' => 'post_pack', 'uses' => 'CallController@postPack']);
        Route::get('calls/getDeparts','CallController@getDeparts');




        Route::resource('locations', 'LocationController', ['except' => ['show']]);

        Route::resource('departmentGrps', 'DepartmentGroupController', ['except' => ['show']]);

        Route::resource('doctors','DoctorController', ['except' => ['show']]);

        // Department
        Route::resource('departments', 'DepartmentController', ['except' => ['show']]);


        Route::resource('packages', 'PackageController', ['except' => ['show']]);

        Route::resource('help', 'HelpController', ['except' => ['show']]);
      //  Route::resource('calls/getDeparts}','CallController@getDeparts');

         Route::get('missed','HelpController@missed');


        Route::get('help/help','HelpController@help');

        Route::get('myform1/ajax/{id}/{tno}',array('as'=>'myform.ajax','uses'=>'HelpController@myformAjax1'));


 
        Route::resource('service', 'ServiceController', ['except' => ['show']]);

        

        // Counter
            Route::resource('counters', 'CounterController', ['except' => ['show']]);
          
            Route::resource('billingcounters', 'BillingCounterController', ['except' => ['show']]);

        //Reports
            Route::group(['prefix' => 'reports', 'as' => 'reports::'], function() {
            // User Report
            Route::get('user', ['as' => 'user', 'uses' => 'UserReportController@index']);
            Route::get('user/{user}/{date}', ['as' => 'user_show', 'uses' => 'UserReportController@show']);

            // Queue list
            Route::get('queuelist/{date}', ['as' => 'queue_list', 'uses' => 'QueueListReportController@index']);
            
            Route::get('queuelist1/{date}', ['as' => 'queue_list1', 'uses' => 'QueueListReportController@show']);
            
           

            // Monthly Report
            Route::get('monthly', ['as' => 'monthly', 'uses' => 'MonthlyReportController@index']);
            Route::get('monthly/{department}/{sdate}/{edate}', ['as' => 'monthly_show', 'uses' => 'MonthlyReportController@show']);

            // Statistical Report
            Route::get('statistical', ['as' => 'statistical', 'uses' => 'StatisticalReportController@index']);
            Route::get('statistical/{date}/{user}/{department}/{counter}', ['as' => 'statistical_show', 'uses' => 'StatisticalReportController@show']);

            // Missed
            Route::get('missed-overtime', ['as' => 'missed', 'uses' => 'MissedOvertimeReportController@index']);
            Route::get('missed-overtime/{date}/{user}/{counter}/{type}', ['as' => 'missed_show', 'uses' => 'MissedOvertimeReportController@show']);


        });

      Route::post('missed-overtime/reissue', ['as' => 'post_reissue', 'uses' => 'MissedOvertimeReportController@reissue']);


/*
            Route::get('token_report', ['as' => 'missed', 'uses' => 'TokenReportController@index']);
            Route::get('token_report/{date}/{user}/{counter}/{type}', ['as' => 'token_report', 'uses' => 'TokenReportController@show']);

*/



        Route::get('token_report', ['as' => 'token_report', 'uses' => 'TokenReportController@index']);
      /*  Route::post('token_report', ['as' => 'post_call', 'uses' => 'TokenReportController@newCall']);
        Route::post('token_report/recall', ['as' => 'post_recall', 'uses' => 'TokenReportController@recall']);
        Route::post('token_report/dept/{department}', ['as' => 'post_dept', 'uses' => 'TokenReportController@postDept']);
        Route::post('token_report/pack/{package}', ['as' => 'post_pack', 'uses' => 'TokenReportController@postPack']);
        Route::get('token_report/getDeparts','TokenReportController@getDeparts');
*/


       Route::post('token_report/reissue', ['as' => 'post_reissue', 'uses' => 'TokenReportController@reissue']);






           
        // Users
        Route::get('users/{user}/password', ['as' => 'get_user_password', 'uses' => 'UserController@getPassword']);
        Route::post('users/{user}/password', ['as' => 'post_user_password', 'uses' => 'UserController@postPassword']);
        Route::resource('users', 'UserController', ['except' => ['show', 'edit', 'update']]);

        // Settings
        Route::get('settings', ['as' => 'settings', 'uses' => 'SettingsController@index']);
        Route::post('settings', ['as' => 'post_settings', 'uses' => 'SettingsController@update']);
        Route::post('settings/company', ['as' => 'post_company', 'uses' => 'SettingsController@companyUpdate']);
        Route::post('settings/overmissed', ['as' => 'post_over_missed', 'uses' => 'SettingsController@overmissedUpdate']);
        Route::post('settings/locale', ['as' => 'post_locale', 'uses' => 'SettingsController@localeUpdate']);


        Route::get('time', ['as' => 'time', 'uses' => 'TimeController@index']);



    });
});


/*
Route::get('add_to_newqueue', ['as' => 'add_to_newqueue', 'uses' => 'AddToNewQueueController@index']);
Route::get('queue', ['as' => 'add_to_queue', 'uses' => 'AddToNewQueueController@index']);




Route::get('queue', ['as' => 'post_add_to_queue', 'uses' => 'AddToNewQueueController@postDept']);

*/
//post_add_to_queue
        // Users
      
        Route::resource('locationusers', 'LocationUserController');
        Route::get('locationusers/{id}', 'UserReportController@show');
        Route::get('locationusers/{user}/edit', ['as' => 'get_user_edit', 'uses' => 'UserController@edit']);




//schedulers
Route::get('time', ['as' => 'time', 'uses' => 'TimeController@index']);
Route::get('getrecords', ['as' => 'time', 'uses' => 'GetRecordController@index']);
Route::get('scheduleQueue', ['as' => 'time', 'uses' => 'ScheduleQueueController@index']);
Route::get('secondQueue', ['as' => 'time', 'uses' => 'SecondQueueController@index']);
Route::get('thirdQueue', ['as' => 'time', 'uses' => 'ThirdQueueController@index']);
Route::get('scheduleQueues', ['as' => 'time', 'uses' => 'ScheduleQueuesController@index']);
Route::get('checklist/{mob}', ['as' => 'time', 'uses' => 'CheckListController@index']);
Route::resource('mychecklist', 'CheckListController@checkList', ['except' => ['show']]);
Route::get('consultation', ['as' => 'consultation', 'uses' => 'ConsultationController@index']);
Route::get('nextdayconsultation', ['as' => 'consultation', 'uses' => 'NextDayConsultationController@index']);
Route::resource('testtimer', 'TestTimeCallController', ['except' => ['show']]);
Route::get('pptimer', ['as' => 'pptimer', 'uses' => 'PPTimeCallController@index']);
Route::get('nonpptimer', ['as' => 'nonpptimer', 'uses' => 'NonPPTimeCallController@index']);

//schedulers





//PPTimeCallController.php

app/Models/Doctor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Doctor extends Model
{
    protected $fillable = ['name', 'doctor_id','specialization_id','specialization','hospital_id'];

     public function calls()
	{
		return $this->hasMany('App\Models\Call');
	}

    public function specialization()
    {
    	return $this->belongsTo('App\Models\Specialization');
    }

    public function hospital()
	{
		return $this->belongsTo('App\Models\Hospital');
	}

}

app/Http/Controllers/DoctorController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Repositories\CallRepository;
use App\Models\Call;
use App\Models\Doctor;
use App\Models\Location;
use App\Models\Specialization;
use App\Models\Hospital;

use DB;

class DoctorController extends Controller
{
    protected $doctor;

    public function __construct(Location $locations)
    {
       
        $this->locations = $locations;
    }

    public function index()
    {

        //$this->authorize('access', Department::class);

       $doctors =  Doctor::all();

     /*  foreach ($doctors as $doctor) {
          
return $doctor->name;

       }/**/
    
       


        return view('user.doctors.index', [
            'doctors' => $doctors
           
           
        ]);
    }

    public function create()
    {
       
      $specializations= Specialization::all();
      $hospitals=Hospital::all();
       
    //dd($hospitals);
        return view('user.doctors.create',['specializations'=>$specializations,'hospitals'=>$hospitals]);
    }

    public function store(Request $request, Doctor $doctor)
    {
    

        $this->validate($request, [
            'name' => 'required',
             'doctor_id' =>'required',
            'specialization_id' =>'required',
             'hospital_id' => 'required'
       ]);

      $specializationname = Specialization::where('id',$request->specialization_id)->first();
        $doctor->name = $request->name;
        $doctor->doctor_id = $request->doctor_id;
        $doctor->specialization_id=$request->specialization_id;
        $doctor->specialization=$specializationname->name;
        $doctor->hospital_id = $request->hospital_id;
        $doctor->save();



        flash()->success('Doctor created');
        return redirect()->route('doctors.index');
    }

    public function edit(Request $request, Doctor $doctor)
    {
        
        $specializations = Specialization::all();
        $hospitals = Hospital::all();
        return view('user.doctors.edit', [
            'doctor' => $doctor, 'specializations' => $specializations, 'hospitals' => $hospitals,
        ]);
    }

    public function update(Request $request, Doctor $doctor )
    {
       
   
        
      
       $specializationname = Specialization::where('id',$request->specialization_id)->first();
        $doctor->name = $request->name;
        $doctor->doctor_id = $request->doctor_id;
        $doctor->specialization_id=$request->specialization_id;
        $doctor->specialization=$specializationname->name;
        $doctor->hospital_id = $request->hospital_id;
        $doctor->save();


        flash()->success('Doctor updated');
        return redirect()->route('doctors.index');
    }
    public function destroy(Request $request, Doctor $doctor)
    {
        //$this->authorize('access', Department::class);

        $doctor->delete();

        flash()->success('Doctor deleted');
        return redirect()->route('doctors.index');
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Repositories\UserRepository;
use App\Models\User;
use App\Repositories\DepartmentRepository;
use App\Models\Department;
use App\Repositories\CounterRepository;
use App\Models\Counter;
use App\Models\Online;
use App\Models\Location;
use Illuminate\Support\Facades\Input;

class UserController extends Controller
{
    protected $users;

    public function __construct(UserRepository $users,DepartmentRepository $departments,CounterRepository $counters)
    {
        $this->users = $users;
        $this->departments = $departments;
        $this->counters = $counters;
    }

    public function index(Request $request)
    {

         $service_users = Online::all('user_id');

      foreach ($service_users as $service_user) {
            $service_user_id[]=$service_user->user_id;
      }
      
        $this->authorize('access', User::class);

        return view('user.users.index', [
            'users' => $this->users->getAll(),
            'departments' =>$this->departments->getAll(),
            'online_user' => $service_user_id,
        ]);
    }

    public function create(Request $request)
    {
        $this->authorize('access', User::class);
        
        return view('user.users.create',['departments' =>$this->departments->getAll(),
            'counters' =>$this->counters->getAll(),'locations' =>Location::all()
            ]);
    }

    public function store(Request $request)
    {
              // dd($request->all());
        $this->authorize('access', User::class);

        $this->validate($request, [
            'name' => 'bail|required',
            'username' => 'bail|required|min:6|unique:users,username',
            'email' => 'bail|required|email|unique:users,email',
            'password' => 'bail|required|min:6|confirmed',
        ]);
       
        $data = $request->all();
       // $data['role'] = 'S';
        $data['password'] = bcrypt($request->password);
       // $date['department_id'] = $request->department;

        //return $data;

        $user = User::create($data);

        flash()->success('User created');
        return redirect()->route('users.index');
    }

    public function getPassword(Request $request, User $user)
    {
        $this->authorize('access', User::class);

        if($user->id==$request->user()->id) abort(404);

        return view('user.users.password', [
            'cuser' => $user,
        ]);
    }

    public function postPassword(Request $request, User $user)
    {
        $this->authorize('access', User::class);

        if($user->id==$request->user()->id) abort(404);

        $this->validate($request, [
            'password' => 'required|confirmed|min:6',
        ]);

        $user->password = bcrypt($request->password);
        $user->save();

        flash()->success('Password changed');
        return redirect()->route('users.index');
    }

    public function destroy(Request $request, User $user)
    {
        $this->authorize('access', User::class);

        $user->delete();

        flash()->success('User deleted');
        return redirect()->route('users.index');
    }

    public function getDepartments(Request $request){
    $data =$request->option;
     return $subcategories  = Department::where('location_id','=',$data)->get();

    }
}

resources/views/user/doctors/create.blade.php
@extends('layouts.app')

@section('title', trans('messages.add').' '.trans('messages.mainapp.menu.doctor'))

@section('content')
    <div id="breadcrumbs-wrapper">
        <div class="container">
            <div class="row">
                <div class="col s12 m12 l12">
                    <h5 class="breadcrumbs-title col s5" style="margin:.82rem 0 .656rem">{{ trans('messages.add') }} {{ trans('messages.mainapp.menu.doctor') }}</h5>
                    <ol class="breadcrumbs col s7 right-align">
                        <li><a href="{{ route('dashboard') }}">{{ trans('messages.mainapp.menu.dashboard') }}</a></li>
                        <li><a href="{{ route('doctors.index') }}">{{ trans('messages.mainapp.menu.doctor') }}</a></li>
                        <li class="active">{{ trans('messages.add') }}</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col s12 m6 offset-m3" style="padding-top:10px;padding-bottom:10px">
                <a class="btn-floating waves-effect waves-light orange tooltipped right" href="{{ route('doctors.index') }}" data-position="top" data-tooltip="{{ trans('messages.cancel') }}"><i class="mdi-navigation-arrow-back"></i></a>
                <form id="add" action="{{ route('doctors.store') }}" method="post">
                    {{ csrf_field() }}
                    <div class="row">
                        <div class="input-field col s12">
                            <label for="name">{{ trans('messages.name') }}</label>
                            <input id="name" type="text" name="name" placeholder="{{ trans('messages.mainapp.menu.doctor') }} {{ trans('messages.name') }}" value="{{ old('name') }}" data-error=".name">
                            <div class="name">
                                @if($errors->has('name'))<div class="error">{{ $errors->first('name') }}</div>@endif
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <label for="doctor_id">{{ trans('Doctor_id') }}</label>
                            <input id="doctor_id" type="text" name="doctor_id" placeholder="{{ trans('doctor_id') }}"  data-error=".doctor_id">
                            <div class="doctor_id">
                                @if($errors->has('doctor_id'))<div class="error">{{ $errors->first('doctor_id') }}</div>@endif
                            </div>
                        </div>
                    </div>
                      <div class="row">
            <div class="input-field col s12">
                <label for="specialization" class="active">{{ trans('Specialization') }}</label>
                    <select id="specialization_id" class="browser-default" name="specialization_id" data-error=".specialization_id">
                      <option value="">Select Specialization</option>
                      @foreach($specializations as $specialization )
                      <option value="{{ $specialization->id}}">{{ $specialization->name}} </option>
                      @endforeach
                        
                    </select>
              <div class="specialization">
                    @if($errors->has('specialization'))<div class="error">{{ $errors->first('specialization') }}</div>@endif
                </div>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <label for="hospital_id" class="active">{{ trans('Hospital') }}</label>
                    <select id="hospital_id" class="browser-default" name="hospital_id" data-error=".hospital_id">
                      <option value="">Select Hospital</option>
                      @foreach($hospitals as $hospital )
                      <option value="{{ $hospital->id}}">{{ $hospital->name}} </option>
                      @endforeach 
                    </select>
              <div class="hospital">
                    @if($errors->has('hospital'))<div class="error">{{ $errors->first('hospital') }}</div>@endif
                </div>
            </div>
        </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <button class="btn waves-effect waves-light right" type="submit">
                                {{ trans('messages.save') }}<i class="mdi-content-save left"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $("#add").validate({
            rules: {
                name: {
                    required: true
                },
                doctor_id: {
                    required: true,
                    digits: true
                },
                specialization_id:{
                    required: true
                   
                },

                hospital_id:{
                    required: true
                    
                },
            },
            errorElement : 'div',
            errorPlacement: function(error, element) {
                var placement = $(element).data('error');
                if (placement) {
                    $(placement).append(error)
                } else {
                    error.insertAfter(element);
                }
            }
        });

    </script>
@endsection

resources/views/user/doctors/edit.blade.php
@extends('layouts.app')

@section('title', trans('messages.edit').' '.trans('messages.mainapp.menu.doctor'))

@section('content')
    <div id="breadcrumbs-wrapper">
        <div class="container">
            <div class="row">
                <div class="col s12 m12 l12">
                    <h5 class="breadcrumbs-title col s5" style="margin:.82rem 0 .656rem">{{ trans('messages.edit') }} {{ trans('messages.mainapp.menu.doctor') }}</h5>
                    <ol class="breadcrumbs col s7 right-align">
                        <li><a href="{{ route('dashboard') }}">{{ trans('messages.mainapp.menu.dashboard') }}</a></li>
                        <li><a href="{{ route('doctors.index') }}">{{ trans('messages.mainapp.menu.doctor') }}</a></li>
                        <li class="active">{{ trans('messages.edit') }}</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col s12 m6 offset-m3" style="padding-top:10px;padding-bottom:10px">
                <a class="btn-floating waves-effect waves-light orange tooltipped right" href="{{ route('doctors.index') }}" data-position="top" data-tooltip="{{ trans('messages.cancel') }}"><i class="mdi-navigation-arrow-back"></i></a>
                <form id="edit" action="{{ route('doctors.update', ['doctors' => $doctor->id]) }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <div class="row">
                        <div class="input-field col s12">
                            <label for="name">{{ trans('messages.name') }}</label>
                            <input id="name" type="text" name="name" placeholder="{{ trans('messages.mainapp.menu.doctor') }} {{ trans('messages.name') }}" value="{{ $doctor->name }}" data-error=".name">
                            <div class="name">
                                @if($errors->has('name'))<div class="error">{{ $errors->first('name') }}</div>@endif
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <label for="doctor_id">{{ trans('Doctor ID') }}</label>
                            <input id="doctor_id" type="text" name="doctor_id" placeholder="{{ trans('Doctor ID') }}" value="{{ $doctor->doctor_id }}" data-error=".doctor_id">
                            <div class="doctor_id">
                                @if($errors->has('doctor_id'))<div class="error">{{ $errors->first('doctor_id') }}</div>@endif
                            </div>
                        </div>
                    </div>
                     <div class="row">
            <div class="input-field col s12">
                <label for="specialization" class="active">{{ trans('Specialization') }}</label>
                    <select id="specialization_id" class="browser-default" name="specialization_id" data-error=".specialization_id">
                      <option value="">Select Specialization</option>
                      @foreach($specializations as $specialization )
                    <option value="{{ $specialization->id}}" {{ $doctor->specialization_id == $specialization->id ? 'selected="selected"' : '' }}>{{ $specialization->name }}</option>
                      @endforeach
                        
                    </select>
              <div class="specialization">
                    @if($errors->has('specialization'))<div class="error">{{ $errors->first('specialization') }}</div>@endif
                </div>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <label for="hospital_id" class="active">{{ trans('Hospital') }}</label>
                    <select id="hospital_id" class="browser-default" name="hospital_id" data-error=".hospital_id">
                      <option value="">Select Hospital</option>
                      @foreach($hospitals as $hospital )
                     <option value="{{ $hospital->id}}" {{ $doctor->hospital_id == $hospital->id ? 'selected="selected"' : '' }}>{{ $hospital->name }}</option>
                      @endforeach
                    </select>
              <div class="hospital">
                    @if($errors->has('hospital'))<div class="error">{{ $errors->first('hospital') }}</div>@endif
                </div>
            </div>
        </div>
                   
                    <div class="row">
                        <div class="input-field col s12">
                            <button class="btn waves-effect waves-light right" type="submit">
                                {{ trans('messages.update') }}<i class="mdi-action-swap-vert left"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $("#edit").validate({
            rules: {
                name: {
                    required: true
                },
                start: {
                    required: true,
                    digits: true
                },
            },
            errorElement : 'div',
            errorPlacement: function(error, element) {
                var placement = $(element).data('error');
                if (placement) {
                    $(placement).append(error)
                } else {
                    error.insertAfter(element);
                }
            }
        });

    jQuery(document).ready(function($){
    $('#location_id').change(function(){

      $.get("{{ url('select-ajax1')}}", 
            { option: $(this).val() },

               function(data) {
                   
                    var model = $('#counter_id');
                    model.empty();

                    $.each(data, function(index, element) {
                        model.append("<option value='"+ element.id +"'>" + element.name + "</option>");
                    });
                });
        });
    });
    </script>
@endsection